---
# handlers file for deploy_web
- name: Restart of web-service for RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"

- name: Restart of web-service for Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"